name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '3.2.2'
      SERVERPOD_PASSWORD_database: 'uX6pFB8oEqqwi_mFoDJQz_zss4F31YGe'
      SERVERPOD_PASSWORD_redis: 'XEN03BhEA2Rl_xPrUSLtez7EHs7zre7q'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Start containers
        working-directory: my_project_server
        run: docker compose up --build -d

      - name: Install dependencies
        working-directory: my_project_server
        run: dart pub get

      - name: Install Serverpod CLI
        working-directory: my_project_server
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: my_project_server
        run: serverpod generate

      - name: Run tests
        working-directory: my_project_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: my_project_server
        run: docker compose down -v
